---
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3307:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_mariadb
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8091:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${ROOT_PASSWORD}

volumes:
  data:

networks:
  default:
    name: mariadb_network
