---
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - config-data:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  data:
  config-data:

networks:
  default:
    name: mongodb_network
