---
services:
  mysql:
    image: mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_NAME}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8090:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}

volumes:
  data:

networks:
  default:
    name: mysql_network
