---
services:
  webspoon:
    image: hiromuhota/webspoon
    container_name: webspoon
    volumes:
      - ./projects:/home/tomcat/.kettle/data/projects
      - pentaho:/home/tomcat/.pentaho
    ports:
      - 3080:8080
    environment:
      - JAVA_OPTS=-Xms${JAVA_MIN_HEAP}m -Xmx${JAVA_MAX_HEAP}m

volumes:
  pentaho:
