---
services:
  redis:
    image: redis
    command: redis-server --port $REDIS_PORT --save 60 1 --loglevel warning --requirepass $REDIS_AUTH
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_AUTH=${REDIS_AUTH}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis

volumes:
  data:
  redisinsight_data:

networks:
  default:
    name: redis_network
