---
services:
  dynamodb:
    image: amazon/dynamodb-local
    working_dir: /home/dynamodblocal
    command: -jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data
    ports:
      - ${DYNAMODB_PORT}:8000
    volumes:
      - ./data:/home/dynamodblocal/data
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - ${DYNAMODB_ADMIN_PORT}:8001
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=${CLI_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${CLI_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${CLI_AWS_REGION}
    depends_on:
      - dynamodb
  aws-cli:
    image: amazon/aws-cli
    command: dynamodb list-tables --endpoint-url http://dynamodb:8000 --region $CLI_AWS_REGION
    environment:
      - AWS_ACCESS_KEY_ID=${CLI_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${CLI_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${CLI_AWS_REGION}
    depends_on:
      - dynamodb
